<Project>
  <PropertyGroup>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>

	<PropertyGroup>
    <NupkgsDirectory>../../../nupkgs</NupkgsDirectory>
		<RestoreAdditionalProjectSources>$(NupkgsDirectory)</RestoreAdditionalProjectSources>
		<PackageOutputPath>$(NupkgsDirectory)</PackageOutputPath>
	</PropertyGroup>
</Project>
